### ISSUE TITLE
Request for License Addition to Labelling-app Repository

### ISSUE THREAD

**Issue by SumaREK** [MagiCzOOz/Labelling-app#1]
Hello @MagiCzOOz ,

I hope this message finds you well. I am very interested in your Labelling-app repository and would like to reuse some parts of the tool. To ensure compliance with licensing and respect for your work, could you please consider adding a license to the repository?

Thank you in advance for your consideration.

**Comment by MagiCzOOz** [comment]
Hello @SumaREK ,

Thank you for your message. Sorry for the response delay. 
The license has been added. I hope this is helpful for you.

**Comment by SumaREK** [comment]
Thanks a lot @MagiCzOOz .
